spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "50m"
              memory: 64Mi
            limits:
              cpu: "500m"
              memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: SPRING_PROFILES_ACTIVE
            value: ocp-dev
              
