---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: xlate
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: xlate@sha256:4b68907b99a464f10b3d36cd34857f244c925844f5574283121cdc1aa5d9a837
        namespace: fuse-assignment
      name: latest
