---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: inbound
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: inbound@sha256:a2862c760a939b4a871971040900397fa32e8f45e63f816d5580e6e4f7a2bc43
        namespace: fuse-assignment
      name: latest
